# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.5.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.5.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/ken/Desktop/research/External Library/L-BFGS/l-bfgs gradient projection"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/ken/Desktop/research/External Library/L-BFGS/l-bfgs gradient projection"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.5.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.5.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/ken/Desktop/research/External Library/L-BFGS/l-bfgs gradient projection/CMakeFiles" "/Users/ken/Desktop/research/External Library/L-BFGS/l-bfgs gradient projection/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/ken/Desktop/research/External Library/L-BFGS/l-bfgs gradient projection/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named L-BFGS-gp

# Build rule for target.
L-BFGS-gp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 L-BFGS-gp
.PHONY : L-BFGS-gp

# fast build rule for target.
L-BFGS-gp/fast:
	$(MAKE) -f CMakeFiles/L-BFGS-gp.dir/build.make CMakeFiles/L-BFGS-gp.dir/build
.PHONY : L-BFGS-gp/fast

L-BFGS-gp.o: L-BFGS-gp.cpp.o

.PHONY : L-BFGS-gp.o

# target to build an object file
L-BFGS-gp.cpp.o:
	$(MAKE) -f CMakeFiles/L-BFGS-gp.dir/build.make CMakeFiles/L-BFGS-gp.dir/L-BFGS-gp.cpp.o
.PHONY : L-BFGS-gp.cpp.o

L-BFGS-gp.i: L-BFGS-gp.cpp.i

.PHONY : L-BFGS-gp.i

# target to preprocess a source file
L-BFGS-gp.cpp.i:
	$(MAKE) -f CMakeFiles/L-BFGS-gp.dir/build.make CMakeFiles/L-BFGS-gp.dir/L-BFGS-gp.cpp.i
.PHONY : L-BFGS-gp.cpp.i

L-BFGS-gp.s: L-BFGS-gp.cpp.s

.PHONY : L-BFGS-gp.s

# target to generate assembly for a file
L-BFGS-gp.cpp.s:
	$(MAKE) -f CMakeFiles/L-BFGS-gp.dir/build.make CMakeFiles/L-BFGS-gp.dir/L-BFGS-gp.cpp.s
.PHONY : L-BFGS-gp.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... L-BFGS-gp"
	@echo "... L-BFGS-gp.o"
	@echo "... L-BFGS-gp.i"
	@echo "... L-BFGS-gp.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

